# FILE: docker-compose.yml BEGINS =======================================
version: '3'

services:
  postgres:
    container_name: fintech_fullstack
    image: postgres:15.4-alpine3.18
    env_file:
      - .env  # Specify the path to your .env file
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

# FILE: docker-compose.yml END    =======================================